Features/task 1
petrareb/kentico-onboarding-cs pull request #2
Opened 2018-09-05 09:37 UTC by petrareb

2018-09-05 10:11 UTC, vaclavm requested changes
Hi Petra, I know you should just create dummy controller but even in the dummy controller there are some rules to follow 👼.

I believe you will enjoy this review as it gives you more information about WebAPI and how to write it. As always, you can ask to anything - I like it more then writting looooooong review 😄.

2018-09-05 10:11 UTC, vaclavm commented on MyOnboarding/src/MyOnboardingApp.Api/Controllers/DefaultController.cs
> +    public class DefaultController : ApiController
I think you have left this in the solution by the accident, right? ♿️

2018-09-05 10:11 UTC, vaclavm commented on MyOnboarding/src/MyOnboardingApp.Api/Controllers/TodoListController.cs
> +    public class TodoListController : ApiController
You should have you controllers methods [async](https://msdn.microsoft.com/en-us/magazine/dn802603.aspx) as it is good for scalability and performance.

Also, you should return [IHttpActionResult](https://docs.microsoft.com/en-us/aspnet/web-api/overview/getting-started-with-aspnet-web-api/action-results) from your methods. You can specify the correct http response based on the request (200, 404, 500).

2018-09-05 10:11 UTC, vaclavm commented on MyOnboarding/src/MyOnboardingApp.Api/Controllers/TodoListController.cs
> +        public IEnumerable<TodoListItem> Post([FromBody]TodoListItem newItem)
POST do not returns all items, it should only return the new one.
You can read more about REST methods and what should they return [here](https://tools.ietf.org/html/rfc7231#section-4.3).

2018-09-05 10:11 UTC, vaclavm commented on MyOnboarding/src/MyOnboardingApp.Api/Controllers/TodoListController.cs
> +        public IEnumerable<TodoListItem> Put(Guid id, [FromBody]TodoListItem item)
PUT don't have to return [anything](https://tools.ietf.org/html/rfc7231#section-4.3.4).

2018-09-05 10:11 UTC, vaclavm commented on MyOnboarding/src/MyOnboardingApp.Api/Controllers/TodoListController.cs
> +        public IEnumerable<TodoListItem> Delete(Guid id)
Delete returns [void](https://tools.ietf.org/html/rfc7231#section-4.3.5).

2018-09-05 10:11 UTC, vaclavm commented on MyOnboarding/src/MyOnboardingApp.Api/Models/TodoListItem.cs
> +    [DataContract]
You don't have to specify DataContract and DataMember as it used in WCF. We are using [WebApi](https://stackoverflow.com/questions/43775132/difference-between-wcf-web-api-wcf-rest-and-web-service), there is no need to specify anything for the REST methods.

2018-09-05 10:11 UTC, vaclavm commented on MyOnboarding/test/MyOnboardingApp.Api.Tests/TodoListControllerTest.cs
> +    public class TodoListControllerTest
You should name the tests using What-When-Then structure => Get_IdSpecified_ReturnsItemWithId. So you can correctly specify the behavior and everyone can see, what you are trying to test.

2018-09-05 10:11 UTC, vaclavm commented on MyOnboarding/test/MyOnboardingApp.Api.Tests/MyOnboardingApp.Api.Tests.csproj
>      <Compile Include="DummyTest.cs" />
Remove this test from the solution, it is not needed anymore.

2018-09-05 11:45 UTC, vaclavm commented on MyOnboarding/test/MyOnboardingApp.Api.Tests/TodoListControllerTest.cs
> +    public class TodoListControllerTest
Also, you should rewrite your tests to check correct status code is returned once you fix the controller 😉

2018-09-05 13:19 UTC, petrareb commented on MyOnboarding/src/MyOnboardingApp.Api/Controllers/DefaultController.cs
> +    public class DefaultController : ApiController
![giphy](https://user-images.githubusercontent.com/40829888/45095234-e3464000-b11d-11e8-9d3b-5d9b2ea54754.gif)

2018-09-07 07:55 UTC, vaclavm requested changes
Hi, Petra. Still, some work left, mostly in the tests. 
Make them really dummy - don't access the List in the controller and test the correct status codes only (except POST).

The test should be unit and should be valid even though you will change in the controller in the further tasks. Right now, your tests fits only the controller now, with List inside.
Also, regarding test have a chat with Hanka about extension method for controller 😉.

Go for it!

2018-09-07 07:55 UTC, vaclavm commented on MyOnboarding/src/MyOnboardingApp.Api/App_Start/JsonSerializerConfig.cs
> +    public static class JsonSerializerConfig
👏

2018-09-07 07:55 UTC, vaclavm commented on MyOnboarding/src/MyOnboardingApp.Api/Controllers/TodoListController.cs
> +            return await Task.FromResult((IHttpActionResult)Ok());
[If you do not return deleted item (which is correct), then NoContent should be returned](https://stackoverflow.com/questions/2342579/http-status-code-for-update-and-delete).

2018-09-07 07:55 UTC, vaclavm commented on MyOnboarding/src/MyOnboardingApp.Api/Controllers/TodoListController.cs
> +            return await Task.FromResult((IHttpActionResult)Ok());
As you are not returning anything in the body, return NoContent is more appropriate.

2018-09-07 07:55 UTC, vaclavm commented on MyOnboarding/src/MyOnboardingApp.Api/Controllers/TodoListController.cs
> +        public async Task<IHttpActionResult> GetAsync(Guid id)
Can be made lambda style!

2018-09-07 07:55 UTC, vaclavm commented on MyOnboarding/src/MyOnboardingApp.Api/Controllers/TodoListController.cs
> +            return await Task.FromResult((IHttpActionResult)Ok(DefaultItem));
You do not have to explicitly type the result here or in any of he methods.

2018-09-07 07:55 UTC, vaclavm commented on MyOnboarding/test/MyOnboardingApp.Api.Tests/TodoListControllerTest.cs
> +        public async Task Post_NewTextSpecifiedInRequestBody_AddsNewItem()
This test is unnecessary. Don't validate that the item was add to List<> as the controller and tests should be dummy

2018-09-07 07:55 UTC, vaclavm commented on MyOnboarding/test/MyOnboardingApp.Api.Tests/TodoListControllerTest.cs
> +        public async Task Post_NewTextSpecifiedInRequestBody_ReturnsCorrectResponse()
This test is good!

2018-09-07 07:55 UTC, vaclavm commented on MyOnboarding/test/MyOnboardingApp.Api.Tests/TodoListControllerTest.cs
> +        public async Task Put_IdSpecifiedTextSpecified_EditsItemWithId()
Don't test the adding of the item into List<>, make it dummier 😉. Remove every test where you validate if something is/isn't in List.

2018-09-07 07:55 UTC, vaclavm commented on MyOnboarding/src/MyOnboardingApp.Api/Controllers/TodoListController.cs
> +        public static List<TodoListItem> Items = new List<TodoListItem>{ DefaultItem };
Make this private and don't use it in tests, make the test dummy.

2018-09-07 07:55 UTC, vaclavm commented on MyOnboarding/src/MyOnboardingApp.Api/Controllers/TodoListController.cs
> +        public static TodoListItem DefaultItem =
Use different Id for dummy purposes, something like 'dummyId' or 'dog' or anything easy.

2018-09-07 07:55 UTC, vaclavm commented on MyOnboarding/test/MyOnboardingApp.Api.Tests/TodoListControllerTest.cs
> +            TodoListController.Items.Add(TestItem);
Do not access TodoListController.Items at all in tests, just test that the test returns correct StatusCode. Update all tests.

2018-09-10 07:03 UTC, vaclavm requested changes
I am still not satisfied with the solution 👼. There is a space to upgrade it a little bit further.

2018-09-10 07:03 UTC, vaclavm commented on MyOnboarding/src/MyOnboardingApp.Api/Controllers/TodoListController.cs
> +        public static readonly TodoListItem S_defaultItem =
This should be private and not used in tests.

2018-09-10 07:03 UTC, vaclavm commented on MyOnboarding/test/MyOnboardingApp.Api.Tests/TodoListControllerTest.cs
> +            Assert.That(expectedItem.Id, Is.EqualTo(itemFromMsg.Id));
`itemFromMsg` should be first in Assert -> _Assert(actual, expected)_

2018-09-10 07:03 UTC, vaclavm commented on MyOnboarding/test/MyOnboardingApp.Api.Tests/TodoListControllerTest.cs
> +            var idToDelete = TodoListController.S_defaultItem.Id;
Don't use `TodoListController.S_defaultItem`, your tests are not valid that way. Because the tests will work even though the `TodoListController.S_defaultItem` is changed -> the test should fail if something in the controller is changed.

2018-09-10 07:03 UTC, vaclavm commented on MyOnboarding/src/MyOnboardingApp.Api/Controllers/TodoListController.cs
> +        public static readonly TodoListItem S_defaultItem =
Once changed to private, change the name with small `s_` as you have in the List<> bellow.

2018-09-10 07:03 UTC, vaclavm commented on MyOnboarding/test/MyOnboardingApp.Api.Tests/Utils/TodoListControllerExtensions.cs
> +    public static class TodoListControllerExtensions
👏

2018-09-10 07:03 UTC, vaclavm commented on MyOnboarding/test/MyOnboardingApp.Api.Tests/Utils/TodoListControllerExtensions.cs
> +        public static async Task<HttpResponseMessage> GetMessageFromAction(this TodoListController controller, Func<TodoListController, Task<IHttpActionResult>> action)
FYI: Could be taken a little bit further by making it generic - it would then work for every Controller (not only TodoListController ) 😉.

2018-09-10 09:38 UTC, vaclavm approved these changes

2018-09-10 09:38 UTC, merged